credentials:
  # Will not explain..
  username:
  password:
options:
  # Sub-domain of your college
  # Example, for the University of West Attica is 'eclass.uniwa.gr'
  baseDomain:
  # Toggle true if you want the results to be printed in csv format instead 
  # of a table (for the unix philosophers)
  plainText: false
  # Ignore the expired assignments
  ignoreExpired: true
  # Export to calendar ICS file
  exportICS: false
  # Exclude courses by course code
  # Can be found at the url of the course' s dashboard
  # Example: https://eclass.uniwa.gr/modules/work/?course=CS152 <-- CS152
  excludedCourses:
    # - CS152
    # - ICE22
  # Exclude assignments by course code and keywords that will be ignored 
  # Use it if you observe a specific pattern your professor uses to exclude 
  # other class' assignments 
  excludedAssignmentsByKeyword:
    # CS666: 
    #   - Δευτέρας
    #   - Τρίτης
    # CS152: 
    #   - ΓΙΑ ΟΣΟΥΣ ΔΕΝ ΕΙΝΑΙ ΓΡΑΜΜΕΝΟΙ ΣΕ ΚΑΠΟΙΟ ΤΜΗΜΑ
